/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package libsSrc.VehicleCalculator.lib.src.main.java.com.vehiclecalculator;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
